source 'https://rubygems.org'

gem 'middleman-core', '~> 4.2.1'
gem 'middleman-cli', '~> 4.2.1'
gem 'middleman-asciidoc', '~> 1.0.0'
gem 'middleman-autoprefixer', '~> 2.8.0'
gem 'middleman-google-analytics', '~> 3.0.0'

gem 'coderay', '~> 1.1.2', require: false
gem 'slim', '~> 3.0.9', require: false
gem 'tzinfo-data', platforms: [:x64_mingw, :mingw]
gem 'wdm', '~> 0.1.1', platforms: [:x64_mingw, :mingw]

group :development do
  gem 'middleman-livereload', '~> 3.4.6'
end
